### ISSUE TITLE
Doesn't reproduce predict_example

### ISSUE THREAD

**Issue by giovannilopez9808** [cmb-chula/SurfUVNet#2]
Hi!
I've read your article: Accurate surface ultraviolet radiation forecasting for clinical applications with deep neural network, We are very interested in applying your model in Monterrey city (Mexico). In that sense, we would like to know some details regarding the repository on GitHub. There is a weights file (.he5), my question is: Do these weights values result from data training, or are they just random values?

I have that doubt because when I clone the repository and execute the forecast (Prediction_example.ipynb), this result is different compared to what is shown. Could you help me to solve that, please?
![image](https://user-images.githubusercontent.com/64244398/191860236-1866d11f-5771-43ea-b5a7-79709902a200.png)

**Comment by waiiinta** [comment]
Sorry for late reply.

Can you show tensorflow and keras version in your environment?

**Comment by giovannilopez9808** [comment]
For tensorflow i have 2.9.1 version and keras is 2.9.0

**Comment by waiiinta** [comment]
Your environment does not meet the requirements of our script,
Tensorflow 1.14.0 and Keras 2.2.5 are used to train our weights.
The mismatch version can alter model prediction and cause model performance to differ from our reports.
